name: cli
description: reset-cli is a powerfull package that allow you to reset your linux system.
version: 1.0.0
repository: https://github.com/nuageeee/reset-linux

environment:
  sdk: ^3.5.3

dependencies:
    os: ^1.0.0
    commander_ui: ^2.0.0
    args: ^2.6.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0